name: README build
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.github/workflows/*.yaml'
  schedule:
    - cron: "0 4 * * *"
  repository_dispatch:
    types: [update-readme]
  workflow_dispatch:
    inputs:
      source_repo:
        description: 'Repository that triggered this update'
        required: false
        default: 'manual'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: github.actor != 'MaybeScripted/GitHub-Actions-Bot' && (github.event_name != 'push' || github.event.head_commit.author.name != 'MaybeScripted/GitHub-Actions-Bot')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Get Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Configure pip cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/cache/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: python -m pip install -r cache/requirements.txt

      - name: Update README file
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          USER_NAME: ${{ secrets.USER_NAME }}
          SOURCE_REPO: ${{ github.event.client_payload.source_repo || 'manual' }}
          SOURCE_BRANCH: ${{ github.event.client_payload.source_branch || 'unknown' }}
          SOURCE_COMMIT: ${{ github.event.client_payload.source_commit || 'unknown' }}
        run: |
          echo "Triggered by: ${{ github.event.client_payload.triggered_by || github.actor }}"
          echo "Source repo: $SOURCE_REPO"
          echo "Source branch: $SOURCE_BRANCH"
          echo "Source commit: $SOURCE_COMMIT"
          python today.py

      - name: Check for changes
        id: changes
        run: |
          git add .
          if git diff --staged --quiet; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "No changes detected, skipping commit"
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "Changes detected, proceeding with commit"
          fi

      - name: Commit and push
        if: steps.changes.outputs.has_changes == 'true'
        run: |
          git config --global user.email "github-actions-bot@maybescripted.github.io"
          git config --global user.name "MaybeScripted/GitHub-Actions-Bot"
          git commit -m "Updated README"
          git push
